# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 16:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_auto_20141216_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}', help_text='PostgreSQL json serialized form of this version of the model.'),
        ),
    ]
